apiVersion: v1
kind: Secret
metadata:
  name: s3-model-secret
  namespace: sridharproject
  annotations:
    serving.kserve.io/s3-endpoint: "minio.sridharproject.svc.cluster.local:9000"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-verifyssl: "0"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin123"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-model-sa
  namespace: sridharproject
secrets:
  - name: s3-model-secret
