apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: student-llm
  namespace: sridharproject
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    serviceAccountName: student-model-sa
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      storageUri: "s3://sridhar-models/student-1b-merged/"
      resources:
        requests:
          cpu: "2"
          memory: "8Gi"
        limits:
          cpu: "4"
          memory: "16Gi"
