apiVersion: v1
kind: Secret
metadata:
  name: mlflow-minio-creds
  namespace: sridharproject
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin123"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: sridharproject
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: sridharproject
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v3.10.0
          command: ["mlflow"]
          args:
            - "server"
            - "--host=0.0.0.0"
            - "--port=5000"
            - "--backend-store-uri=sqlite:///mlflow/mlflow.db"
            - "--default-artifact-root=s3://mlflow-artifacts/"
            - "--serve-artifacts"
            - "--artifacts-destination=s3://mlflow-artifacts/"
            - "--allowed-hosts=*"
            - "--cors-allowed-origins=*"
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-minio-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-minio-creds
                  key: AWS_SECRET_ACCESS_KEY
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio.sridharproject.svc.cluster.local:9000"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: sridharproject
  labels:
    app: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mlflow
  namespace: sridharproject
spec:
  to:
    kind: Service
    name: mlflow
  port:
    targetPort: http
