apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-trainjob-access
  namespace: sridharproject
rules:
- apiGroups:
  - trainer.kubeflow.org
  resources:
  - trainjobs
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-trainjob-access
  namespace: sridharproject
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-trainjob-access
subjects:
- kind: ServiceAccount
  name: pipeline-runner-dspa
  namespace: sridharproject
