# This rule is not used by the project distillation-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over distillation.rhoai.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: distillation-operator
    app.kubernetes.io/managed-by: kustomize
  name: distillationjob-admin-role
rules:
- apiGroups:
  - distillation.rhoai.example.com
  resources:
  - distillationjobs
  verbs:
  - '*'
- apiGroups:
  - distillation.rhoai.example.com
  resources:
  - distillationjobs/status
  verbs:
  - get
