---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - distillation.rhoai.example.com
  resources:
  - distillationjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - distillation.rhoai.example.com
  resources:
  - distillationjobs/finalizers
  verbs:
  - update
- apiGroups:
  - distillation.rhoai.example.com
  resources:
  - distillationjobs/status
  verbs:
  - get
  - patch
  - update
